name: Homebrew Bottle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: macos-26
    env:
      HOMEBREW_TAP: ${{ github.repository_owner }}/stable
      HOMEBREW_ROOT_URL: https://ghcr.io/v2/${{ github.repository_owner }}/stable
      HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
      HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Configure a Homebrew Tap
      run: |
        brew tap-new --no-git $HOMEBREW_TAP
        rm -r $(brew --repo $HOMEBREW_TAP)
        ln -s $(pwd) $(brew --repo $HOMEBREW_TAP)

    - name: Build a Homebrew Bottle
      run: |
        brew install --build-bottle $HOMEBREW_TAP/metalchat
        brew bottle --json --merge $HOMEBREW_TAP/metalchat
        #brew pr-upload --upload-only --root-url $HOMEBREW_ROOT_URL
        git diff HEAD HEAD~1
